export const branches = [
  {
    id: 1,
    name: "Mumbai Central Branch",
    branchHead: "Rajesh Sharma",
    branchContactNo: "+91 9876543210",
    branchEmail: "mumbai.central@company.com",
    branchAddress: "12th Floor, Orbit Plaza, Lower Parel",
    branchCity: "Mumbai",
    branchState: "Maharashtra",
    department: "Sales",
    team: "Team A",
    totalEmployees: 42,
    workingHours: "10:00 AM - 7:00 PM",
    timezone: "Asia/Kolkata",
    holidays: "Sunday",
    salesExecutives: 18,
    activeLeads: 220,
    totalClosures: 54,
    revenue: "₹48,00,000",
    monthlyTarget: "₹60,00,000",
    achievement: "80%",
    supportEmail: "support.mumbai@company.com",
    supportPhone: "+91 9988776655",
    updated_at: "2025-11-10",
    created_at: "2024-03-18",
    status: "Active",
  },
  {
    id: 2,
    name: "Delhi North Branch",
    branchHead: "Anita Verma",
    branchContactNo: "+91 9123456780",
    branchEmail: "delhi.north@company.com",
    branchAddress: "Regal Towers, Connaught Place",
    branchCity: "New Delhi",
    branchState: "Delhi",
    department: "Sales",
    team: "Team B",
    totalEmployees: 35,
    workingHours: "9:30 AM - 6:30 PM",
    timezone: "Asia/Kolkata",
    holidays: "Sunday",
    salesExecutives: 14,
    activeLeads: 190,
    totalClosures: 46,
    revenue: "₹39,50,000",
    monthlyTarget: "₹55,00,000",
    achievement: "72%",
    supportEmail: "support.delhi@company.com",
    supportPhone: "+91 8899001122",
    updated_at: "2025-11-11",
    created_at: "2024-04-05",
    status: "Active",
  },
  {
    id: 3,
    name: "Bangalore East Branch",
    branchHead: "Rohit Nair",
    branchContactNo: "+91 9090876765",
    branchEmail: "blr.east@company.com",
    branchAddress: "Tech Park Phase 2, Whitefield",
    branchCity: "Bangalore",
    branchState: "Karnataka",
    department: "Sales",
    team: "Team C",
    totalEmployees: 50,
    workingHours: "9:00 AM - 6:00 PM",
    timezone: "Asia/Kolkata",
    holidays: "Saturday, Sunday",
    salesExecutives: 20,
    activeLeads: 250,
    totalClosures: 60,
    revenue: "₹52,75,000",
    monthlyTarget: "₹65,00,000",
    achievement: "81%",
    supportEmail: "support.blr@company.com",
    supportPhone: "+91 7766554433",
    updated_at: "2025-11-12",
    created_at: "2024-02-20",
    status: "Active",
  },
  {
    id: 4,
    name: "Hyderabad Hitech Branch",
    branchHead: "Siddharth Rao",
    branchContactNo: "+91 9988112233",
    branchEmail: "hyd.hitech@company.com",
    branchAddress: "Plot 14, Hitech City Road",
    branchCity: "Hyderabad",
    branchState: "Telangana",
    department: "Sales",
    team: "Team D",
    totalEmployees: 38,
    workingHours: "10:00 AM - 7:00 PM",
    timezone: "Asia/Kolkata",
    holidays: "Sunday",
    salesExecutives: 16,
    activeLeads: 175,
    totalClosures: 41,
    revenue: "₹33,20,000",
    monthlyTarget: "₹50,00,000",
    achievement: "66%",
    supportEmail: "support.hyd@company.com",
    supportPhone: "+91 9000998877",
    updated_at: "2025-11-05",
    created_at: "2024-01-10",
    status: "Inactive",
  },
  {
    id: 5,
    name: "Pune West Branch",
    branchHead: "Kunal Patil",
    branchContactNo: "+91 9988221144",
    branchEmail: "pune.west@company.com",
    branchAddress: "Baner Road Corporate Park",
    branchCity: "Pune",
    branchState: "Maharashtra",
    department: "Sales",
    team: "Team E",
    totalEmployees: 29,
    workingHours: "9:30 AM - 6:00 PM",
    timezone: "Asia/Kolkata",
    holidays: "Sunday",
    salesExecutives: 12,
    activeLeads: 140,
    totalClosures: 34,
    revenue: "₹28,10,000",
    monthlyTarget: "₹40,00,000",
    achievement: "70%",
    supportEmail: "support.pune@company.com",
    supportPhone: "+91 7788996655",
    updated_at: "2025-11-15",
    created_at: "2023-12-08",
    status: "Active",
  }
];
