export const moduleData = [
  {
    id: 1,
    module_key: "DASHBOARD_MODULE",
    name: "Dashboard",
    description: "Overall CRM overview and insights",
    status: true,
  },
  {
    id: 2,
    module_key: "USER_MODULE",
    name: "Users",
    description: "User & team management",
    status: true,
  },
  {
    id: 3,
    module_key: "LEAD_MODULE",
    name: "Leads",
    description: "Lead capture, tracking & qualification",
    status: true,
  },
  {
    id: 4,
    module_key: "MEETING_MODULE",
    name: "Meetings",
    description: "Meeting scheduling, tracking & outcomes",
    status: true,
  },
  {
    id: 5,
    module_key: "TASK_MODULE",
    name: "Tasks_Reminders",
    description: "Tasks, follow-ups & reminders",
    status: true,
  },
  {
    id: 6,
    module_key: "SOURCE_MODULE",
    name: "Sources",
    description: "Lead sources & campaigns",
    status: true,
  },
  {
    id: 7,
    module_key: "DEPARTMENT_MODULE",
    name: "Departments",
    description: "Department & team organization",
    status: true,
  },
  {
    id: 8,
    module_key: "BRANCH_MODULE",
    name: "Branches",
    description: "Branch configuration & mapping",
    status: true,
  },
  {
    id: 9,
    module_key: "ROLE_MODULE",
    name: "Roles",
    description: "Role definitions & access levels",
    status: true,
  },
  {
    id: 10,
    module_key: "RIGHTS_MODULE",
    name: "Rights",
    description: "Fine-grained permissions / rights",
    status: true,
  },
  {
    id: 11,
    module_key: "SUBADMIN_MODULE",
    name: "Sub Admins",
    description: "Sub-admin creation & assignment",
    status: true,
  },
  {
    id: 12,
    module_key: "REPORTS_MODULE",
    name: "Reports",
    description: "Analytics, KPIs & exports",
    status: true,
  },
  {
    id: 13,
    module_key: "SETTINGS_MODULE",
    name: "Settings",
    description: "System & configuration settings",
    status: true,
  },
];
