export const dummyUsers = [
  {
    id: 1,
    image: "https://randomuser.me/api/portraits/men/11.jpg",
    name: "Amit Sharma",
    email: "amit.sharma@example.com",
    phone: "9876543210",
    role: "Super Admin",
    department: "Sales",
    branch: "Delhi",
    city: "New Delhi",
    company: "NextHikes",
    isLogin: "Online",
    status: true,
  },
  {
    id: 2,
    image: "https://randomuser.me/api/portraits/women/21.jpg",
    name: "Priya Verma",
    email: "priya.verma@example.com",
    phone: "8596321470",
    role: "Admin",
    department: "Marketing",
    branch: "Gurgaon",
    city: "Gurugram",
    company: "NextHikes",
    isLogin: "Offline",
    status: false,
  },
  {
    id: 3,
    image: "https://randomuser.me/api/portraits/men/31.jpg",
    name: "Rahul Gupta",
    email: "rahul.gupta@example.com",
    phone: "9988776655",
    role: "Manager",
    department: "IT",
    branch: "Noida",
    city: "Noida",
    company: "NextHikes",
    isLogin: "Online",
    status: true,
  },
  {
    id: 4,
    image: "https://randomuser.me/api/portraits/men/41.jpg",
    name: "Admin",
    email: "sandeep.kumar@example.com",
    phone: "9911223344",
    role: "Executive",
    department: "Human Resources",
    branch: "Delhi",
    city: "Delhi",
    company: "NextHikes",
    isLogin: "Offline",
    status: true,
  },

  // {
  //   id: 5,
  //   image: "https://randomuser.me/api/portraits/women/51.jpg",
  //   name: "Neha Singh",
  //   email: "neha.singh@example.com",
  //   phone: "7788996655",
  //   role: "Executive",
  //   department: "Finance",
  //   branch: "Noida",
  //   city: "Noida",
  //   company: "NextHikes",
  //   isLogin: "Online",
  //   status: false,
  // },
  // {
  //   id: 6,
  //   image: "https://randomuser.me/api/portraits/men/61.jpg",
  //   name: "Rohit Yadav",
  //   email: "rohit.yadav@example.com",
  //   phone: "9001234567",
  //   role: "Developer",
  //   department: "IT",
  //   branch: "Gurgaon",
  //   city: "Gurugram",
  //   company: "NextHikes",
  //   isLogin: "Offline",
  //   status: true,
  // },
  // {
  //   id: 7,
  //   image: "https://randomuser.me/api/portraits/women/71.jpg",
  //   name: "Kavita Joshi",
  //   email: "kavita.joshi@example.com",
  //   phone: "9023456789",
  //   role: "Designer",
  //   department: "UI/UX",
  //   branch: "Delhi",
  //   city: "Delhi",
  //   company: "NextHikes",
  //   isLogin: "Online",
  //   status: true,
  // },
  // {
  //   id: 8,
  //   image: "https://randomuser.me/api/portraits/men/81.jpg",
  //   name: "Vikas Mehta",
  //   email: "vikas.mehta@example.com",
  //   phone: "9887766554",
  //   role: "Support",
  //   department: "Customer Support",
  //   branch: "Delhi",
  //   city: "New Delhi",
  //   company: "NextHikes",
  //   isLogin: "Offline",
  //   status: false,
  // },
  // {
  //   id: 9,
  //   image: "https://randomuser.me/api/portraits/women/12.jpg",
  //   name: "Ritika Kapoor",
  //   email: "ritika.kapoor@example.com",
  //   phone: "9090909090",
  //   role: "Sales Executive",
  //   department: "Sales",
  //   branch: "Gurgaon",
  //   city: "Gurugram",
  //   company: "NextHikes",
  //   isLogin: "Online",
  //   status: true,
  // },
  // {
  //   id: 10,
  //   image: "https://randomuser.me/api/portraits/men/14.jpg",
  //   name: "Dhruv Malhotra",
  //   email: "dhruv.malhotra@example.com",
  //   phone: "9898989898",
  //   role: "Manager",
  //   department: "IT",
  //   branch: "Noida",
  //   city: "Noida",
  //   company: "NextHikes",
  //   isLogin: "Offline",
  //   status: false,
  // },
  // {
  //   id: 11,
  //   image: "https://randomuser.me/api/portraits/women/19.jpg",
  //   name: "Simran Kaur",
  //   email: "simran.kaur@example.com",
  //   phone: "9876501234",
  //   role: "Executive",
  //   department: "Marketing",
  //   branch: "Delhi",
  //   city: "Delhi",
  //   company: "NextHikes",
  //   isLogin: "Online",
  //   status: true,
  // },
  // {
  //   id: 12,
  //   image: "https://randomuser.me/api/portraits/men/55.jpg",
  //   name: "Arjun Khanna",
  //   email: "arjun.khanna@example.com",
  //   phone: "9765123450",
  //   role: "Developer",
  //   department: "IT",
  //   branch: "Noida",
  //   city: "Noida",
  //   company: "NextHikes",
  //   isLogin: "Offline",
  //   status: true,
  // },
  // {
  //   id: 13,
  //   image: "https://randomuser.me/api/portraits/women/44.jpg",
  //   name: "Tanya Mehra",
  //   email: "tanya.mehra@example.com",
  //   phone: "9123456780",
  //   role: "HR",
  //   department: "Human Resources",
  //   branch: "Gurgaon",
  //   city: "Gurugram",
  //   company: "NextHikes",
  //   isLogin: "Online",
  //   status: true,
  // },
  // {
  //   id: 14,
  //   image: "https://randomuser.me/api/portraits/men/66.jpg",
  //   name: "Shubham Jain",
  //   email: "shubham.jain@example.com",
  //   phone: "9098765432",
  //   role: "QA Engineer",
  //   department: "Testing",
  //   branch: "Delhi",
  //   city: "New Delhi",
  //   company: "NextHikes",
  //   isLogin: "Offline",
  //   status: false,
  // },
  // {
  //   id: 15,
  //   image: "https://randomuser.me/api/portraits/women/92.jpg",
  //   name: "Anjali Rawat",
  //   email: "anjali.rawat@example.com",
  //   phone: "9856231470",
  //   role: "Designer",
  //   department: "UI/UX",
  //   branch: "Gurgaon",
  //   city: "Gurugram",
  //   company: "NextHikes",
  //   isLogin: "Online",
  //   status: true,
  // },
  // {
  //   id: 16,
  //   image: "https://randomuser.me/api/portraits/men/95.jpg",
  //   name: "Yash Saxena",
  //   email: "yash.saxena@example.com",
  //   phone: "9812345678",
  //   role: "Developer",
  //   department: "IT",
  //   branch: "Delhi",
  //   city: "Delhi",
  //   company: "NextHikes",
  //   isLogin: "Offline",
  //   status: true,
  // },
  // {
  //   id: 17,
  //   image: "https://randomuser.me/api/portraits/women/82.jpg",
  //   name: "Megha Tiwari",
  //   email: "megha.tiwari@example.com",
  //   phone: "9888899990",
  //   role: "Support",
  //   department: "Customer Support",
  //   branch: "Noida",
  //   city: "Noida",
  //   company: "NextHikes",
  //   isLogin: "Online",
  //   status: false,
  // },
  // {
  //   id: 18,
  //   image: "https://randomuser.me/api/portraits/men/24.jpg",
  //   name: "Deepak Mishra",
  //   email: "deepak.mishra@example.com",
  //   phone: "9797979797",
  //   role: "Sales Lead",
  //   department: "Sales",
  //   branch: "Delhi",
  //   city: "Delhi",
  //   company: "NextHikes",
  //   isLogin: "Offline",
  //   status: true,
  // },
  // {
  //   id: 19,
  //   image: "https://randomuser.me/api/portraits/women/35.jpg",
  //   name: "Pooja Reddy",
  //   email: "pooja.reddy@example.com",
  //   phone: "9345678901",
  //   role: "Executive",
  //   department: "Finance",
  //   branch: "Gurgaon",
  //   city: "Gurugram",
  //   company: "NextHikes",
  //   isLogin: "Online",
  //   status: true,
  // },
  // {
  //   id: 20,
  //   image: "https://randomuser.me/api/portraits/men/36.jpg",
  //   name: "Harsh Raj",
  //   email: "harsh.raj@example.com",
  //   phone: "9001122334",
  //   role: "Manager",
  //   department: "Operations",
  //   branch: "Noida",
  //   city: "Noida",
  //   company: "NextHikes",
  //   isLogin: "Offline",
  //   status: false,
  // }
];
